import { useState } from 'react';
import { FileText, Copy, Share2, Printer, CheckCircle, Loader, Sparkles, RefreshCw } from 'lucide-react';
import { askClaude } from '../lib/claude';
import AIBadge from '../components/AIBadge';

const RECIPIENTS = [
  { id: 'mcd', label: 'MCD Commissioner', full: 'The Commissioner, Municipal Corporation of Delhi' },
  { id: 'pwd', label: 'PWD Secretary', full: 'The Secretary, Public Works Department, GNCT of Delhi' },
  { id: 'djb', label: 'DJB Chief Engineer', full: 'The Chief Engineer, Delhi Jal Board' },
  { id: 'cm', label: "Chief Minister's Office", full: "The Principal Secretary to Chief Minister, Government of NCT of Delhi" },
  { id: 'lg', label: "LG's Office", full: 'The Secretary to Lieutenant Governor, Raj Niwas, Delhi' },
];

const SYSTEM_PROMPT = `You are an expert in drafting formal complaint letters to Indian government authorities in Delhi.
Generate a professional formal complaint letter in the official Indian government letter format.
The letter must include:
- Reference number (auto-generate as CF-YYYY-XXXXX)
- Date
- Proper addressing
- Subject line
- Well-structured body with specific details, legal references where relevant (Civic Amenities, RTI Act 2005 if applicable)
- Polite but firm tone demanding timely action
- Proper closing

Return ONLY the letter text — no JSON, no explanation, no markdown. Start directly with "Ref: CF-...".`;

export default function LetterGenerator() {
  const [form, setForm] = useState({ issue: '', name: '', address: '', ward: '', recipient: 'mcd' });
  const [letter, setLetter] = useState('');
  const [hindiLetter, setHindiLetter] = useState('');
  const [loading, setLoading] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [showHindi, setShowHindi] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  const update = (k, v) => setForm(p => ({ ...p, [k]: v }));

  const generate = async () => {
    if (!form.issue.trim() || !form.name.trim()) return;
    setLoading(true);
    setLetter('');
    setHindiLetter('');
    setShowHindi(false);
    setError('');
    try {
      const recipientInfo = RECIPIENTS.find(r => r.id === form.recipient);
      const userMsg = `Complainant Name: ${form.name}
Address: ${form.address || 'Not specified'}
Ward: ${form.ward || 'Not specified'}
Recipient: ${recipientInfo.full}
Issue Description: ${form.issue}
Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`;

      const result = await askClaude(SYSTEM_PROMPT, userMsg, 1200);
      setLetter(result);
    } catch {
      setError('Failed to generate letter. Please check your API key and try again.');
    } finally {
      setLoading(false);
    }
  };

  const translateToHindi = async () => {
    if (!letter || translating) return;
    setTranslating(true);
    try {
      const hindi = await askClaude(
        'You are a professional translator. Translate the following formal complaint letter from English to Hindi. Preserve the formal letter format and all details exactly. Return only the translated letter.',
        letter,
        1200
      );
      setHindiLetter(hindi);
      setShowHindi(true);
    } catch {
      setError('Translation failed. Try again.');
    } finally {
      setTranslating(false);
    }
  };

  const copy = () => {
    const text = showHindi ? hindiLetter : letter;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const printLetter = () => window.print();

  const whatsapp = () => {
    const text = encodeURIComponent((showHindi ? hindiLetter : letter).slice(0, 1000) + '...\n\n[Generated by CivicFix AI]');
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  const displayLetter = showHindi ? hindiLetter : letter;

  return (
    <div className="min-h-screen py-8 page-enter">
      <style>{`@media print { .no-print { display: none !important; } .print-only { display: block !important; } }`}</style>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 no-print">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <h1 className="font-display font-extrabold text-3xl text-navy-900">AI Letter Generator</h1>
            <AIBadge text="Claude Powered" />
          </div>
          <p className="text-gray-500 font-body text-sm">Generate a formal complaint letter to government authorities — ready to submit in seconds.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Form */}
          <div className="card p-6 space-y-4 h-fit">
            <h2 className="font-display font-bold text-lg text-navy-900">Your Details</h2>

            <div>
              <label className="label">Describe Your Issue *</label>
              <textarea value={form.issue} onChange={e => update('issue', e.target.value)}
                className="input-field resize-none h-32 text-sm"
                placeholder="e.g. There is a large pothole on MG Road near the metro station which has been causing accidents for the past 2 weeks. Multiple vehicles have been damaged..." />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="label">Your Full Name *</label>
                <input type="text" value={form.name} onChange={e => update('name', e.target.value)}
                  className="input-field text-sm" placeholder="Arjun Sharma" />
              </div>
              <div>
                <label className="label">Ward / Area</label>
                <input type="text" value={form.ward} onChange={e => update('ward', e.target.value)}
                  className="input-field text-sm" placeholder="Ward 45, Dwarka" />
              </div>
            </div>

            <div>
              <label className="label">Your Address</label>
              <input type="text" value={form.address} onChange={e => update('address', e.target.value)}
                className="input-field text-sm" placeholder="H-23, Sector 6, Dwarka, New Delhi - 110075" />
            </div>

            <div>
              <label className="label">Send To *</label>
              <div className="grid grid-cols-1 gap-2">
                {RECIPIENTS.map(r => (
                  <label key={r.id}
                    className={`flex items-center gap-3 p-3 rounded-xl border-2 cursor-pointer transition-all
                      ${form.recipient === r.id ? 'border-flame-500 bg-flame-500/5' : 'border-gray-200 hover:border-gray-300'}`}>
                    <input type="radio" name="recipient" value={r.id} checked={form.recipient === r.id}
                      onChange={() => update('recipient', r.id)} className="accent-flame-500" />
                    <div>
                      <p className="font-display font-semibold text-sm text-navy-900">{r.label}</p>
                      <p className="text-[10px] text-gray-400 font-body">{r.full}</p>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm text-red-600 font-body">{error}</div>
            )}

            <button onClick={generate} disabled={loading || !form.issue.trim() || !form.name.trim()}
              className={`w-full flex items-center justify-center gap-2 py-3 rounded-xl font-display font-bold text-sm transition-all
                ${loading || !form.issue.trim() || !form.name.trim()
                  ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                  : 'bg-flame-500 text-white shadow-lg shadow-flame-500/25 hover:bg-flame-600 hover:-translate-y-0.5'}`}>
              {loading
                ? <><Loader size={16} className="animate-spin" /> Generating Letter…</>
                : <><Sparkles size={16} /> Generate Letter</>}
            </button>
          </div>

          {/* Letter Preview */}
          <div className="space-y-4">
            {loading && (
              <div className="card p-8 flex flex-col items-center justify-center gap-3 min-h-64">
                <div className="flex items-center gap-2 text-flame-400">
                  <div className="w-2 h-2 bg-flame-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                  <div className="w-2 h-2 bg-flame-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                  <div className="w-2 h-2 bg-flame-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  <span className="text-sm font-body ml-1">CivicFix AI is thinking...</span>
                </div>
                <p className="text-xs text-gray-400 font-body">Drafting your formal complaint letter…</p>
              </div>
            )}

            {letter && !loading && (
              <>
                {/* Action buttons */}
                <div className="flex items-center gap-2 flex-wrap">
                  <button onClick={copy}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-display font-semibold bg-navy-900 text-white hover:bg-navy-800 transition-all">
                    {copied ? <CheckCircle size={13} /> : <Copy size={13} />}
                    {copied ? 'Copied!' : 'Copy Text'}
                  </button>
                  <button onClick={printLetter}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-display font-semibold bg-white border-2 border-gray-200 text-gray-700 hover:border-gray-300 transition-all">
                    <Printer size={13} /> Download PDF
                  </button>
                  <button onClick={whatsapp}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-display font-semibold bg-green-500 text-white hover:bg-green-600 transition-all">
                    <Share2 size={13} /> Share WhatsApp
                  </button>
                  {!hindiLetter && (
                    <button onClick={translateToHindi} disabled={translating}
                      className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-display font-semibold bg-indigo-500 text-white hover:bg-indigo-600 transition-all disabled:opacity-60">
                      {translating ? <Loader size={13} className="animate-spin" /> : '🇮🇳'}
                      {translating ? 'Translating…' : 'View in Hindi'}
                    </button>
                  )}
                  {hindiLetter && (
                    <button onClick={() => setShowHindi(s => !s)}
                      className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-display font-semibold bg-indigo-500 text-white hover:bg-indigo-600 transition-all">
                      <RefreshCw size={13} />
                      {showHindi ? 'View English' : 'View Hindi'}
                    </button>
                  )}
                </div>

                {/* Language toggle tag */}
                {showHindi && <div className="flex items-center gap-2"><span className="text-xs text-indigo-500 font-display font-semibold">🇮🇳 Hindi Version</span><AIBadge text="AI Translated" /></div>}

                {/* Letter card */}
                <div className="card border-l-4 border-flame-500 p-6">
                  <div className="flex items-center gap-2 mb-4">
                    <FileText size={16} className="text-flame-500" />
                    <span className="font-display font-bold text-sm text-navy-900">Formal Complaint Letter</span>
                    <AIBadge />
                  </div>
                  <pre className="text-sm text-gray-700 font-body leading-relaxed whitespace-pre-wrap">{displayLetter}</pre>
                </div>

                <p className="text-xs text-gray-400 font-body text-center">⚡ Generated by CivicFix AI · Review before sending · AI suggestions only</p>
              </>
            )}

            {!letter && !loading && (
              <div className="card p-10 flex flex-col items-center justify-center gap-3 text-center min-h-64 border-dashed">
                <FileText size={40} className="text-gray-200" />
                <p className="font-display font-semibold text-gray-400">Your letter will appear here</p>
                <p className="text-xs text-gray-300 font-body">Fill the form and click Generate Letter</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Print-only letter */}
      <div className="hidden print-only p-12">
        {letter && <pre style={{ fontFamily: 'Times New Roman, serif', fontSize: '12pt', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{showHindi ? hindiLetter : letter}</pre>}
      </div>
    </div>
  );
}
